% TEST_LDPC_ENCODER Script to test our LDPC decoder implementation
% and compare it with the one in Matlab's Communication Toolbox

clc;
clear;

function_mapper;

aux = load('Hsparse.mat');

H = makeh(aux.Hsparse); %  generate sparse parity check matrix

m = size(H,1); % number of parity bits
n = size(H,2); % codeword length
k = n - m;     % number of information bits

% generate random binary data
s = randi([0 1], [1 k]);

%if you do not have Comm. Toolbox, read the data from the file evalData.mat
%load evalData;

tic; % start timer
cw = ldpcencoder(s, H); % do the encoding
disp('My code (full): '); toc; % stop the timer


% Compare with the LDPC encoder provided by Matlab's Comm. Toolbox
% If you do not have Comm. Toolbox, comment the following lines and use
% cw_MCT and its correspondind s from evalData.mat

enc = comm.LDPCEncoder(H); % initialize encoder object
tic;
cw_MCT = step(enc, s');
disp('Matlab (just encoding): '); toc;

if any(cw~=cw_MCT')
    error('test_ldpc_encoder:differsFromMCT', 'The CW obtained differs from the result of Matlab''s Comm. Toolbox');
else
    fprintf(1, 'The result generated by our implementation is identical to that produced by Matlab''s Comm. Toolbox LDPC encoder\n');
end



